# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CYB3RL4NG
url: "https://gems-cyberlang.github.io/"
base_url: ""
permalink: /:title/

# Build settings
# theme: academic-jekyll-theme
data:
  settings:
    menu:
      - name: About
        leet-name: AB0UT
        url: /about
      - name: Timeline
        leet-name: T1M3L1N3
        url: /timeline
      - name: Blog
        leet-name: B10G
        url: /blog
    social:
      # fa-class is the Font Awesome class for the icon
      - fa-class: fab fa-github
        link: https://github.com/gems-cyberlang
        title: CYB3RL4NG's GitHub organization
      - fa-class: fab fa-instagram
        link: https://instagram.com/cyb3rl4ng
        title: CYB3RL4NG's Instagram
      - fa-class: fa-solid fa-rss
        link: /feed.xml
        title: Atom (RSS-like) feed
    contact:
      title: Team Liaison
      email: something@umd.edu
plugins:
  - jekyll-feed
